### ISSUE TITLE
【要修正】VARCHAR(数字）の数字部分の修正

### ISSUE THREAD

**Issue by kohamamiku** [dicokmr/simple-web-api#10]
## 現在の状態
現在、テーブル定義のフィールド部分は以下の状態にある。
```
text VARCHAR(8192) not null comment'メッセージ'
    ,created_at TIMESTAMP(3) not null comment'生成日時'
    ,receiver_name VARCHAR(256) not null comment'受信者名'
    ,email VARCHAR(512) not null comment'メールアドレス'
```

## 概要
`VARCHAR(8192)`の数字の部分がなぜこの数字になったのかとの議論が上がり、書き方について認識の齟齬がでた。そのため、**正しい認識を身につけてから、修正**を行う。
議論は以下の流れである。

![image](https://user-images.githubusercontent.com/42823688/45525575-8ed24d00-b80e-11e8-85f3-c57f456e08f6.png)

**Comment by dicokmr** [comment]
> maven では

ここが気になりました。なぜ maven の話が出てくるのか？

**Comment by dicokmr** [comment]
MySQLの公式リファレンスをみたら良いかも
https://dev.mysql.com/doc/refman/5.6/ja/char.html

**Comment by kohamamiku** [comment]
> maven では
maven は Java プログラムをビルドするためのツールなので、この文章についていることがおかしいですね。私の聞き間違えかもしれません。
正しくは mysql は、です。
