### ISSUE TITLE
Flywayをアプリにどのように組み込みたいか議論

### ISSUE THREAD

**Issue by dicokmr** [dicokmr/simple-web-api#14]
## 目的
「このアプリがどのようにFlywayを使い、その結果、どのようなメリットを得ようとしているのか？」

ここの認識が @kohamamiku と @dicokmr の間でズレてしまっている。
このIssueですり合わせを行うことで、やらなければいけないことの明確化を行いたい。

**Comment by dicokmr** [comment]
## @dicokmr の考え

以下のような仕組みを取り入れることで、環境構築を意識することなくアプリが動く環境を作成する。

初回起動時
1. アプリケーションを起動する
1. Flywayのマイグレーションが実行される
1. テーブルが作成される
1. 起動完了

次回以降
1. アプリケーションを起動する
1. Flywayのマイグレーションが実行されるが、すでに環境が最新になっているため何もしない
1. 起動完了

**Comment by kohamamiku** [comment]
##  @kohamamiku の考え
正直、flyway について調べて、**DB マイグレーションを実行するためのツールで、DB の状態をバージョン管理でき、ツール経由でSQLを実行することができるもの**と理解はしていましたが、どのファイルをどのような内容で作成してそれを実現するのか、は分かっておりませんでした。

そのため、SQL ファイルの作成からデータベースの作成、flyway の導入などは様々なサイトの情報を頼りに手探りで行なっているというのが現状です。

「@dicokmr の考え」を読み、異論はなく、理解することができますが、プルリクのコードを読んで、内容がなぜそうなるのかの理解がまだできていないので、本日中に解決したいと考えています。
